using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AssignTexture : MonoBehaviour
{
    public ComputeShader shader;

    public int texResolution = 256;

    private Renderer rend;

    private RenderTexture outputTexture;

    private int kernelHandle;
    // Start is called before the first frame update
    void Start()
    {
        outputTexture = new RenderTexture( texResolution, texResolution,0);
        outputTexture.enableRandomWrite = true;
        outputTexture.Create();

        rend = GetComponent<Renderer>();
        rend.enabled = true;

        InitShader();
    }

    private void InitShader()
    {
        kernelHandle = shader.FindKernel("CSMain");
        shader.SetTexture(kernelHandle,"Result",outputTexture);
        rend.material.SetTexture("_MainTex",outputTexture);
        
        DispatchShader(texResolution/16,texResolution/16);
    }

    private void DispatchShader(int x, int y)
    {
        shader.Dispatch(kernelHandle,x,y,1);
    }
    
    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyUp(KeyCode.A))
        {
            DispatchShader(texResolution / 8, texResolution / 8);
        }
    }
    
    
}
